import * as Yup from "yup";
import { PinkValues, NetworkInfo, NetworkId, ContractType } from "../types";
import robot_bestia from "../assets/robot-bestia.jpeg";
import BN from "bn.js";

export const PinkFormSchema = Yup.object().shape({
  prompt: Yup.string().min(3, "Description is too short").required(),
  // fileUpload: Yup.mixed()
  //   .required("A file is required")
  //   .test(
  //     "fileSize",
  //     "File too large",
  //     (value) => value && value.size <= 100
  //   ),
});

export const endpoint = "wss://rpc.shibuya.astar.network";

export const BN_ZERO = new BN(0);

export const networks: Array<NetworkInfo> = [
  {
    endpoint: "wss://rpc.shibuya.astar.network",
    pinkContractAddress: "ZQgRzVGamwEvpkU1LzkT4b7EdtHq6PtH7GmEfyTv1HzQJvv"
  },
  {
    endpoint: "wss://rpc.astar.network",
    pinkContractAddress: "0"
  }
];

export const dryRunCallerAddress =
  "5DPDFJi6rcooALEpR5gSbR8jgUU6YerEHRkAv3Sk8MDoRTke";

export const DEFAULT_MODEL = `https://api-inference.huggingface.co/models/Joeythemonster/anything-midjourney-v-4-1`;

export const PINK_DESCRIPTION = "The collection of Pink Robots generated by AI";
export const initialPinkValues: PinkValues = {
  prompt: "", 
  contractType: ContractType.PinkPsp34,
  ipfs: "ipfs://dummyeidmni6viczb4w6c5knhfoqd26wkuvgn7fz6i4eurz7vo4svhb5lze/metadata.json", 
  aimodel: DEFAULT_MODEL, 
  imageData: new Uint8Array(),
  aiImage: robot_bestia,
  customImage: robot_bestia,
  tokenId: 0,
  networkId: NetworkId.Shibuya,
};

export const contractAddress = networks[initialPinkValues.networkId].pinkContractAddress;